image:
  name: pavelkh09/frontend:latest
  pullSecret: dockerhub-cred
 
backend:
  port: 80
 
resources:
  requests:
    cpu: "60m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "120Mi"
 
config:
  NODE_ENV: "production"
 
ingress:
  host: front.p-kh.ru
  tlsSecret: frontend-api-tls
  clusterIssuer: letsencrypt-prod
 
hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: 80

static:
   enabled: true
   path: /static